# ============================================================
#  setup-env.ps1 — Environment Config (writes Git Bash .bashrc)
# ============================================================
param(
    [string]$GitUser = "",
    [string]$GitEmail = "",
    [string]$ProxyUrl = "",
    [string]$ApiBaseUrl = "",
    [string]$ApiKey = "",
    [string]$ApiModel = "",
    [string]$ClaudeVersion = "2.1.150"
)

$ErrorActionPreference = "Stop"
$MARKER = "# >>> dev-setup auto config >>>"
$END    = "# <<< dev-setup auto config <<<"

$bashrc = "$env:USERPROFILE\.bashrc"
if (-not (Test-Path $bashrc)) { New-Item -ItemType File -Path $bashrc -Force | Out-Null }

$content = Get-Content $bashrc -Raw -ErrorAction SilentlyContinue
if (-not $content) { $content = "" }

# Remove old config block
if ($content -match [regex]::Escape($MARKER)) {
    $content = $content -replace "(?s)$MARKER.*$END", ""
}

# Build new config block
function To-UnixPath($winPath) {
    return $winPath -replace '\\', '/' -replace '^C:', '/c'
}

$lines = @()
$lines += ""
$lines += $MARKER
$lines += "# Auto-generated by dev-setup on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$lines += ""

# npm global path
$lines += 'export PATH="$HOME/.npm-global:$HOME/.npm-global/bin:$PATH"'
$lines += ""

# Git identity
if ($GitUser) {
    $lines += "# Git identity"
    $lines += "export GIT_AUTHOR_NAME=`"$GitUser`""
    $lines += "export GIT_COMMITTER_NAME=`"$GitUser`""
    $lines += ""
}

# Conda (if exists)
$condaPaths = @("$env:USERPROFILE\Miniconda3", "$env:USERPROFILE\anaconda3")
foreach ($cp in $condaPaths) {
    if (Test-Path "$cp\Scripts\conda.exe") {
        $lines += "# Conda"
        $lines += "export CONDA_ROOT=`"$(To-UnixPath $cp)`""
        $lines += 'export PATH="$CONDA_ROOT:$CONDA_ROOT/Scripts:$CONDA_ROOT/Library/bin:$PATH"'
        $lines += ""
        break
    }
}

# Node.js
$nodePath = (Get-Command node.exe -ErrorAction SilentlyContinue).Source
if ($nodePath) {
    $nodeDir = To-UnixPath (Split-Path -Parent $nodePath)
    $lines += "# Node.js"
    $lines += "export NODE_HOME=`"$nodeDir`""
    $lines += 'export PATH="$NODE_HOME:$PATH"'
    $lines += ""
}

# Proxy / VPN
if ($ProxyUrl) {
    $lines += "# Proxy / VPN"
    $lines += "export HTTP_PROXY=`"$ProxyUrl`""
    $lines += "export HTTPS_PROXY=`"$ProxyUrl`""
    $lines += "export http_proxy=`"$ProxyUrl`""
    $lines += "export https_proxy=`"$ProxyUrl`""
    $lines += 'export NO_PROXY="localhost,127.0.0.1,.local"'
    $lines += ""
}

# AI Backend (Claude Code)
if ($ApiBaseUrl -and $ApiKey) {
    $lines += "# AI Backend (Claude Code)"
    $lines += "export ANTHROPIC_BASE_URL=`"$ApiBaseUrl`""
    $lines += "export ANTHROPIC_API_KEY=`"$ApiKey`""
    if ($ApiModel) {
        $lines += "export CLAUDE_MODEL=`"$ApiModel`""
    }
    $lines += ""
}

# Claude Code alias
$lines += "alias claude=`"claude.cmd`""
$lines += ""

$lines += $END
$lines += ""

$newBlock = $lines -join "`r`n"
Set-Content -Path $bashrc -Value ($content.TrimEnd() + "`r`n" + $newBlock) -Encoding UTF8

Write-Host "Environment config written to: $bashrc"

# Summary
Write-Host ""
Write-Host "Configured environment variables:" -ForegroundColor Yellow
if ($GitUser)     { Write-Host "  GIT_AUTHOR_NAME = $GitUser" }
if ($ProxyUrl)    { Write-Host "  HTTP_PROXY     = $ProxyUrl" }
if ($ApiBaseUrl)  { Write-Host "  ANTHROPIC_BASE_URL = $ApiBaseUrl" }
if ($ApiModel)    { Write-Host "  CLAUDE_MODEL       = $ApiModel" }
Write-Host "  ANTHROPIC_API_KEY = *** (set)"
Write-Host ""
Write-Host "Open Git Bash and run: source ~/.bashrc"

